---
title: "Syllabus: Automated Data Collection"
subtitle: "Spring 2024"
editor: 
  markdown: 
    wrap: 72
---

## **Course details**

+------------------+--------------------------------------------------+
| Seminar:         | Übung - Methoden der Vergleichenden              |
|                  | Regierungslehre                                  |
+------------------+--------------------------------------------------+
| Time:            | Tuesday, 15:30 – 17:00,  February 13 to May 28   |
+------------------+--------------------------------------------------+
| Place:           | C -108 Methodenlabor - groß/ Telefonlabor (A 5,  |
|                  | 6 Bauteil C)                                     |
+------------------+--------------------------------------------------+
| Language:        | English                                          |
+------------------+--------------------------------------------------+
| Instructor:      | David Schweizer, M.A.,                           |
|                  | david.schweizer\@uni-mannheim.de                 |
+------------------+--------------------------------------------------+
| Office hours:    | In-person (A 340) or via Zoom, Tuesday 13:45 --  |
|                  | 15:15, please make an appointment by e-mail      |
+------------------+--------------------------------------------------+
| Course website:  |                                                  |
+------------------+--------------------------------------------------+
| Syllabus as PDF  |                                                  |
+------------------+--------------------------------------------------+

## **Course description**

**\
**Against the background of the ever-increasing availability of
(unstructured) online data, the goal of this course is to equip the
students with the necessary skills to collect large quantities of data
for their own research projects, to process the data, and to automate
this workflow in a reproducible way.

The course introduces students to automated data collection using a very
practical approach with the R programming language. The course consists
of three major modules. First, you will be guided into the programming
language and learn the fundamentals of R. No prior experience with R is
necessary. Among other things, we will cover how to import, transform,
and visualize data. Second, we will focus on the workflow for
reproducible research. For example, this includes version control via
Github. Third, we will cover static and dynamic web scraping as well as
APIS’s from a conceptual perspective and use these tools to collect web
data. Finally, we will also learn how to automate this process.

## **Prerequisites**

There are no prerequisites for this course, except the willingness to
familiarise yourself with the R programming language.

## **Course requirements**

**Active participation and preparation:**

Attending the weekly sessions and reading assigned articles and chapters
before class. Use Slack to post any questions or discuss with your peers
if you do not understand concepts. Usually, I post questions to think
about regarding the readings. Keep them in mind while reading.

**Short presentation**

Throughout the semester, I will assign you in groups of 2-3 to
participate in the TidyTuesday challenge
(<https://github.com/rfordatascience/tidytuesday>). The goal is to
produce anything from simple plots to advanced graphics and present your
work process in the next session.

**Data project (100% of your grade):**

Creation of multiple visualizations of (political) data. While it is
possible to produce static visualizations and hand in a PDF, ideally the
visualizations are part of an interactive (web) dashboard. The
visualization project has to be submitted via ILIAS. Late submissions
will result in deductions of 1/3 of a grade point per day. **In case of
any questions or problems, please get in touch with me early.
Deadline:** January 18, 2024, 23:59.

::: panel-tabset
## Content

::: {style="font-size: 80%;"}
-   Your final project should relate to a research question broadly
    related to political science and comparative politics.

-   First, you should describe the motivation for your visualization
    project.

-   Second, make a theoretical argument for the relationships you are
    investigating.

-   Third, describe the data source.

-   Fourth, annotate your coding (import, transformation, ...)
    extensively.
:::

## Quantity

::: {style="font-size: 80%;"}
-   It is difficult to determine a exact "number of plots" needed. Of
    course, you can display much more information in an interactive
    Shiny app than in a static dashboard.

-   You should produce *enough* plots (visualizations) to effectively
    address your research question. Description is totally fine!

-   Note: This is also where the individual office hour comes into play!
:::

## Quality

::: {style="font-size: 80%;"}
-   We have spoken a lot about how we can produce elegant graphs.

-   Therefore, the design of the visualizations will make up a
    considerable share of your grade.

-   Remember? **C**ontrast, **R**epetition, **A**lignment,
    and **P**roximity

-   Creating your own theme!

-   All the *little* things: Titles, captions, accompanying text,
    colors, different aesthetics, ...

-   Here, there is clearly potential for bonus points for effort.
:::
:::

## **Organization & Learning Resources**

**Course website, Slack, and ILIAS:**

The plan is to use primarily the course website and Slack for providing
the structure of the seminar and communication, respectively.
Nevertheless, you will also receive mails via ILIAS. Make sure to
regularly check your university e-mail address.

-   You can find the course website here:
    [Link](https://datavisualizationfall2023.netlify.app/ "https://datavisualizationfall2023.netlify.app/")

-   The ILIAS seminar name is: Ü Methoden der Vergleichenden
    Regierungslehre: Data Visualization for Comparative Politics \[WÜB\]
    \[1. PG\] (HWS 2023). Ensure that you have access to the system and
    that e-mails sent over ILIAS are forwarded to the e-mail account you
    check regularly.

-   If you have contacted me with a question via any channel and you did
    not hear back after 2 days (except over the weekend), please just
    send me your question again!

**Office hours:**

-   In-person (A 340) or via Zoom, Thu 15:30 -- 16:30, please make an
    appointment by e-mail.

-   If you have a specific question or problem (e.g., finding a research
    question), please tell me before coming to the office hours (when
    making the appointment). This way , I can also prepare for it and
    thereby making our meeting more productive and constructive.

**Covid-19 (and general illness):**

-   If you feel ill or have symptoms, please be considerate of your
    fellow students and yourself(!). Just let me know by e-mail.

**Students with disabilities or chronic illnesses:**

-   Please contact me or the Office of Student Affairs if you need
    special assistance due to disabilities or chronic illnesses.

-   And please do this early in the semester so that we can make the
    appropriate arrangements immediately.

**If you need support:**

Of course, you can always talk directly to me if you feel comfortable
with the question. It is important to note that the [University's
Equality and Diversity
Office](https://www.uni-mannheim.de/gleichstellung/beratung/) supports
and advises you in cases of discrimination or sexual harassment. The
responsible contact person in such a case is Dipl.-Psych. Ute Pfründer.
She is trained to deal with such incidents and will keep everything
strictly confidential. No action will be taken without your express
consent. Further counseling services offered by the university can be
found via this
[link](https://www.uni-mannheim.de/studium/beratung-und-service/beratungswegweiser/).

## **Textbooks**

The primary readings for this seminar are chapters from the following
books:

-   Cairo, Alberto*. The truthful art: Data, charts, and maps for
    communication*. New Riders, 2016. *Free access via Katalog Primo (UB
    Mannheim)*

-   Healy, Kieran. *Data visualization: a practical introduction*.
    Princeton University Press, 2018. *Free access via Katalog Primo and
    free online: https://socviz.co/*

-   Wilke, Claus E. *Fundamentals of Data Visualization*. O'Reilly
    Media, 2018). *Free access via Katalog Primo and free online:
    https://clauswilke.com/dataviz/*

## **Course Schedule**

+----------+------------+-----------------------------+
| **Week** | **Date**   | **Topic**                   |
+----------+------------+-----------------------------+
| 1        | 13.02.2024 | Intro Session               |
+----------+------------+-----------------------------+
| 2        | 20.02.2024 | The Tidyverse               |
+----------+------------+-----------------------------+
| 3        | 27.02.2024 | Data Wrangling              |
+----------+------------+-----------------------------+
| 4        | 05.03.2024 | Making plots                |
+----------+------------+-----------------------------+
| 5        | 12.03.2024 | Version control I           |
+----------+------------+-----------------------------+
| 6        | 19.03.2024 | Version control II          |
+----------+------------+-----------------------------+
| 7        | 26.03.2024 | No Session; Easter Break    |
+----------+------------+-----------------------------+
| 8        | 02.04.2024 | No Session, Easter Break    |
+----------+------------+-----------------------------+
| 9        | 09.04.2024 | APIs                        |
+----------+------------+-----------------------------+
| 10       | 16.04.2024 | Webscraping I: Intro        |
+----------+------------+-----------------------------+
| 11       | 23.04.2024 | Webscraping II: Static      |
+----------+------------+-----------------------------+
| 12       | 30.04.2024 | Webscraping II: Interactive |
+----------+------------+-----------------------------+
| 13       | 07.05.2024 | Interactive I               |
+----------+------------+-----------------------------+
| 14       | 14.05.2024 | Interactive II              |
+----------+------------+-----------------------------+
| 15       | 21.05.2024 | Interactive III             |
+----------+------------+-----------------------------+
| 16       | 28.05.2024 | Closing Session             |
+----------+------------+-----------------------------+
