---
title: "Annotations"
subtitle: "Week 09"
description: ""
author: ""
date: "Nov 02, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-09/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

You can find a template for today's group work [**here**](https://ilias.uni-mannheim.de/goto.php?target=file_1449999_download&client_id=ILIAS)**.**

# To Do's before our session

::: panel-tabset
## Read

-   Chapter 17: The principle of proportional ink in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/proportional-ink.html)
-   Chapter 18: Handling overlapping points in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/overlapping-points.html)
-   Chapter 19: Common pitfalls of color use in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/color-pitfalls.html)
-   Chapter 22: Tites, captions, and tables in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/figure-titles-captions.html)
-   Chapter 5: Graph tables, add labels, make notes in Healy, Datavisualization. [Link to free online version](https://socviz.co/workgeoms.html#workgeoms)

**Helpful and interesting readings:**

-   [Tutorial by Cara Thompson](https://www.cararthompson.com/talks/user2022/)

## Think

-   Questions to think about for the readings:

    -   When is annotation helpful and when does it clutter our graph? Can there be too much annotation? When is it most effective?
:::
