---
title: "Interactivity II"
subtitle: "Week 13"
description: ""
author: ""
date: "Nov 30, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-13/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

You can find a zip folder with R scripts for Shiny apps and the respective data [**here**](https://ilias.uni-mannheim.de/goto.php?target=file_1460658_download&client_id=ILIAS).

-   All Shiny apps use either *constituency_shapes_vote.RDS* or *constituency_geometry_vote.RDS* as data, both files are stored in the *data* folder. The R script used for the data processing is called *raw_data_processing.R* and makes use of the *various .csv* files and the *.shp file* in the *raw data* folder.

-   *shiny_app.R* allows you to run a 'basic' Shiny app displaying a histogram of vote shares for the 2017 German federal election allowing you to choose the party.

-   *shiny_dashboard_bslib.R* incorporates the same code, but renders the Shiny app as part of a dashboard.

-   Similar to a flexdashboard, we can create multiple pages on our dashboard. *shinydashboard_multiple_pages_bslib.R* demonstrates this.

-   Finally, *advanced_shiny_app_map.R* introduces reactivity combined with an interactive plot based on the ggiraph package. Based on your selection on the map, the accompanying table will update.

# To Do's before our session

::: panel-tabset
## Read

-   Chapter 1, Your first Shiny app in Wickham, Mastering Shiny. [Link to free online version](https://mastering-shiny.org/basic-app.html).

-   [R Shiny, Get Started: Welcome to Shiny.](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/)

## Think

-   Questions to think about for the readings:

    -   Can you implement the examples on your own device? Try to follow the practical examples and run these Shiny apps!
:::
