---
title: "Comparisons"
subtitle: "Week 08"
description: ""
author: ""
date: "Oct 26, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-08/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

-   You can find the R markdown to follow along the coding example as well as with the task for the group work (and with the necessary data) [**here**](https://ilias.uni-mannheim.de/goto.php?target=fold_1447642&client_id=ILIAS). Create an R project and store all files in the respective folder. You can a file with "solutions" [**here**](https://ilias.uni-mannheim.de/goto.php?target=fold_1447642&client_id=ILIAS)**.**

-   In addition, you can find further examples on how to create small multiples, sparklines, slope graphs, and bump charts [**here**](https://ilias.uni-mannheim.de/goto.php?target=fold_1447647&client_id=ILIAS). Again, in order to run everything smoothly, I recommend to create an R project and store all the files in this folder.

# To Do's before our session

::: panel-tabset
## Read

-   Chapter 9: Visualizing many distributions at once in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/boxplots-violins.html)
-   Chapter 21: Multi-panel figures in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/multi-panel-figures.html)

**Helpful and interesting readings:**

-   [Blog post by Mike Bostock](https://observablehq.com/@mbostock/methods-of-comparison-compared)

-   [Blog post by Edward Tufte](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR)

-   [Lollipop charts](https://uc-r.github.io/lollipop)

## Think

-   Questions to think about for the readings:

    -   What is your favorite way to visualize comparisons?
:::
