---
title: "Uncertainty"
subtitle: "Week 06"
description: ""
author: ""
date: "Oct 12, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-06/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

You can find the coding example and data [on ILIAS](https://ilias.uni-mannheim.de/goto.php?target=fold_1441801&client_id=ILIAS).

# To Do's before our session

::: panel-tabset
## (Voluntary) exercise

Try to run both R markdown files under Materials in week 5 and extend the code as described.

This is not a mandatory exercise. However, I strongly recommend that you try to do it. Being able to extend existing code will be essential for creating a great visualization for your final examination! If there are any questions, please do not hesitate to contact me via e-mail before our next session.

## Read

-   Chapter 4 and 11 in Cairo, The Truthful Art
    -   Please access the chapter via Katalog Primo (University library)
-   Chapter 7: Visualizing distributions: Histograms and density plots in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/histograms-density-plots.html)

**Helpful and interesting readings:**

-   [Blog post by Cedric Scherer](https://www.cedricscherer.com/2021/06/06/visualizing-distributions-with-raincloud-plots-and-how-to-create-them-with-ggplot2/)

-   Chapter 16: Visualizing uncertainty in Wilke, Fundamentals of Data Visualization. [Link to free online version](https://clauswilke.com/dataviz/visualizing-uncertainty.html)

-   Chapter 7 in Cairo, The Truthful Art

    -   Please access the chapter via Katalog Primo (University library)

## Think

-   Questions to think about for the readings:

    -   Why is it important to communicate uncertainty in our plots?
:::
