---
title: "Interactivity I"
subtitle: "Week 10"
description: ""
author: ""
date: "Nov 09, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-10/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

You find the materials to follow along the applied examples as a ZIP file [**here**](https://ilias.uni-mannheim.de/goto.php?target=file_1452333_download&client_id=ILIAS). You should extract the files and make use of the R project in the folder. The folder includes the raw election and structural data as well as the transformed data. With the transformed data you can run the R Markdown files. These allow you to create a simple flexdashboard, a flexdashboard with multiple pages, and a flexdashboard using Shiny (interactive) elements. In order to to run the R markdown files you need to install the package *flexdashboard* and *shiny*.

```{r eval = F, echo = T}
install.packages("flexdashboard")
install.packages("shiny")
```

# To Do's before our session

::: panel-tabset
## Read - Have a look at the examples

-   [flexdashboard by R Studio](https://pkgs.rstudio.com/flexdashboard/)

-   [R Shiny](https://shiny.posit.co/r/gallery/)

**Helpful and interesting readings - Have a look at the respective introductions**

-   [Mastering Shiny](https://mastering-shiny.org/index.html)
-   [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/)

## Think

-   Questions to think about for the readings:

    -   How would you visualize your data in an interactive way or via a flexdashboard?
:::
