---
title: "Designing a Graph"
subtitle: "Week 02"
description: ""
author: ""
date: "Sep 14, 2023"
listing:
  - id: slides
    contents:
      - ../slides/week-02/*.qmd
    type: table
    fields: [title, subtitle, date]
    #date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      subtitle: "Session"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Seminar slides

::: {#slides}
:::

# Materials

You can find the R script for this session [**here**](https://ilias.uni-mannheim.de/goto.php?target=file_1429846_download&client_id=ILIAS).

# To Do's before our session

::: panel-tabset
## Install & Join

-   Make sure R and RStudio is installed and works

    -   Instructions can be found on the course website

-   Join the course Slack channel!

    -   Invitation will follow tomorrow

-   Join the Dataquest team!

    -   Invitation will follow in the next days

## Read

-   Chapter 1: Look at data in Healy, Data Visualization

    -   [Link to free online version](https://socviz.co/lookatdata.html#lookatdata)

-   Chapter 2: The Five Qualities of Great Visualizations in Cairo, The Truthful Art

    -   Please access the chapter via Katalog Primo (University library)

-   Chapter 2: Visualizing data: Mapping data onto aesthetics, in Wilke, Fundamentals of Data Visualization

    -   [Link to free online version](https://clauswilke.com/dataviz/aesthetic-mapping.html)

    Further reading:

-   Chapter 3: Make a Plot in Healy, Data Visualization

    -   [Link to free online version](https://socviz.co/makeplot.html)

## Think

-   Questions to think about for the readings

    -   Why do we use visualizations?

    -   What do we need in order to create great visualizations?

    -   How do we determine what kind of visualization should be used? (Bar plot, pie chart,...)
:::
